# NumPy
- Short for Numerical Python
- Foundational Package for Numerical computing in python
- Provides an ndarray object which is an efficient multidimensional array providing fast array oriented operations
- Provides a lot of functions

In [2]:
import numpy as np

# Creating ndarrays

##### Creating ndarray from an object

In [3]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [4]:
type(a1)

numpy.ndarray

In [5]:
t1 = (1,2,3,4,5)
a1 = np.array(t1)
a1

array([1, 2, 3, 4, 5])

In [6]:
a1 = np.array(range(1,11))
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a1.shape

(10,)

In [8]:
a1.dtype

dtype('int32')

In [9]:
a1.ndim

1

In [14]:
a1 = np.array([[1,2,3], [4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a1.shape

(2, 3)

In [16]:
a1.ndim

2

In [18]:
a1 = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
a1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
a1.shape

(2, 2, 2)

In [20]:
a1.ndim

3

In [21]:
a = np.array([1,2,3,4,5], dtype = float)
a

array([1., 2., 3., 4., 5.])

In [22]:
a.dtype

dtype('float64')

In [23]:
a = np.array([1.5,2.6,3.1,4.8,5.2], dtype = int)
a

array([1, 2, 3, 4, 5])

In [24]:
a.dtype

dtype('int32')

### Typecasting ndarrays

In [25]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [26]:
a = a.astype(float)
a

array([1., 2., 3., 4., 5.])

In [27]:
a = a.astype(int)
a

array([1, 2, 3, 4, 5])

### Creating ndarrays by specifying a range

In [20]:
a1 = np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a1 = np.arange(0,21,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a1 = np.arange(10, dtype = float)
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Creating ndarrays of ones

In [31]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [33]:
np.ones((5,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Creating ndarray of zeros

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Creating ndarray of a specific value

In [35]:
np.full((4,5), fill_value = 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

### Creating an identity matrix

In [39]:
np.eye(5)   # Identity matrix is a square matrix where elements of the principal diagonal are 1 and others 0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# --------------------------------------------------------------------------------------
# Operations on ndarrays

In [40]:
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [41]:
# list
l = [1,2,3,4,5,6]
l + 2

TypeError: can only concatenate list (not "int") to list

In [42]:
a1 + 2

array([3, 4, 5, 6, 7, 8])

In [43]:
a2 = np.array([4,5,6,7,8,9])
a2

array([4, 5, 6, 7, 8, 9])

In [44]:
a1 + a2

array([ 5,  7,  9, 11, 13, 15])

In [45]:
a1 + [2,3,4,5,6,7]

array([ 3,  5,  7,  9, 11, 13])

In [46]:
a1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [47]:
print(a1)
print(a2)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [39]:
a1 * a2

array([ 4, 10, 18, 28, 40, 54])

In [48]:
a1 = np.array([2,4,6,8,10])
a1 / 2

array([1., 2., 3., 4., 5.])

In [49]:
a1 // 2

array([1, 2, 3, 4, 5], dtype=int32)

In [50]:
a1 % 3

array([2, 1, 0, 2, 1], dtype=int32)

In [51]:
a1 ** 2

array([  4,  16,  36,  64, 100], dtype=int32)

In [52]:
a2 = np.array([2,3,4,5,6])
a1 ** a2

array([      4,      64,    1296,   32768, 1000000], dtype=int32)

In [41]:
a1

array([ 2,  4,  6,  8, 10])

In [52]:
2 / a1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [51]:
l1 = [1,2,3,4,5,6]
l1 < 4

TypeError: '<' not supported between instances of 'list' and 'int'

In [53]:
a1 = np.array([1,2,3,4,5,6])
a1 < 4

array([ True,  True,  True, False, False, False])

In [55]:
# list
l1 = [9,1,4,5,3,6]
l2 = [7,4,2,1,6,7]
l1 < l2

False

In [56]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,7])

In [57]:
a1 < a2

array([ True,  True, False, False,  True,  True])

In [58]:
a1 > a2

array([False, False,  True,  True, False, False])

In [46]:
a1 <= a2

array([ True,  True, False, False,  True,  True])

In [59]:
a1 >= a2

array([False, False,  True,  True, False, False])

In [47]:
a1 == a2

array([False, False, False, False, False, False])

In [60]:
# Operation between two ndarrays not possible if shapes are not same
a1 = np.array([1,2,3,4,5])
a2 = np.array([2,3,4,5,6,7])

a1 + a2

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

## Indexing and Slicing ndarrays

In [61]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a[0]

0

In [63]:
a[1]

1

In [64]:
a[6]

6

In [65]:
a[-1]

9

In [66]:
a[-2]

8

In [67]:
a[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [68]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a[-8:-3]

array([2, 3, 4, 5, 6])

In [70]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Reshape and Transpose

In [71]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
a.shape

(16,)

In [73]:
a.ndim

1

In [74]:
a = a.reshape((16,1))
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [75]:
a.shape

(16, 1)

In [76]:
a.ndim

2

In [77]:
a = a.reshape((1,16))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [78]:
a.shape

(1, 16)

In [79]:
a.ndim

2

In [80]:
a.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
a.reshape((2,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [161]:
a = np.arange(36)
a.reshape(1,36)
a.reshape(2,18)
a.reshape(3,12)
a.reshape(4,9)
a.reshape(6,6)
a.reshape(9,4)
a.reshape(12,3)
a.reshape(18,2)
a.reshape(36,1)
print('Possible 2D shape : ', 9)

Possible 2D shape :  9


In [83]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

# ----------------------------------------------------------------------------------

# Functions

In [84]:
a = np.array([2,4,3,6,5,8,7,9,1,0])
a

array([2, 4, 3, 6, 5, 8, 7, 9, 1, 0])

In [87]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
s = np.square(a)
s

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [89]:
np.sqrt(s)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [90]:
np.sqrt(16)

4.0

In [91]:
a = np.array([8,27,64])
np.cbrt(a)

array([2., 3., 4.])

In [80]:
np.abs([-1,2,3,-5,-6,-2,6])

array([1, 2, 3, 5, 6, 2, 6])

In [92]:
abs(-8)

8

In [93]:
np.add([1,2,3],[4,5,6])

array([5, 7, 9])

In [94]:
np.subtract([4,5,6],[1,2,3])

array([3, 3, 3])

In [95]:
np.multiply([1,2,3],[2,3,4])

array([ 2,  6, 12])

In [96]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,5])

In [98]:
np.maximum(a1,a2)

array([3, 4, 4, 5, 6, 6])

In [99]:
np.minimum(a1,a2)

array([2, 1, 2, 1, 3, 5])

In [100]:
np.greater(a1,a2)

array([False, False,  True,  True, False,  True])

In [101]:
np.less(a1,a2)

array([ True,  True, False, False,  True, False])

In [102]:
a1 = np.arange(21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [103]:
np.mean(a1)

10.0

In [106]:
np.mean([1,2,3,4,5,6,7,8,9])

5.0

In [107]:
np.var([1,2,3,4,5,6,7,8,9])

6.666666666666667

In [108]:
np.std([1,2,3,4,5,6,7,8,9])

2.581988897471611

In [109]:
np.median(a1)

10.0

In [110]:
a1.mean()

10.0

In [111]:
a1.var()

36.666666666666664

In [112]:
a1.std()

6.0553007081949835

In [113]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [115]:
a.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

In [117]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
a.min()

1

In [119]:
a.max()

10

In [120]:
a.sum()

55

In [121]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [122]:
a.shape

(8, 8)

In [123]:
a.mean()

31.5

In [124]:
a.mean(axis = 0)

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [126]:
a.mean(axis = 1)

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [127]:
a.std()

18.472953201911167

In [128]:
a.std(axis = 0)

array([18.33030278, 18.33030278, 18.33030278, 18.33030278, 18.33030278,
       18.33030278, 18.33030278, 18.33030278])

In [129]:
a.std(axis = 1)

array([2.29128785, 2.29128785, 2.29128785, 2.29128785, 2.29128785,
       2.29128785, 2.29128785, 2.29128785])

In [130]:
a.max()

63

In [131]:
a.max(axis = 0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [132]:
a.max(axis = 1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [133]:
x = np.array([10,30,80,20,40])
x

array([10, 30, 80, 20, 40])

In [134]:
np.argmax(x)             # returns the index of maximum element

2

In [135]:
np.argmin(x)             # returns the index of minimum element

0

In [136]:
a1 = np.array([2,1,5,4,3,5,6,7,3,10,2,3]).reshape(3,4)
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [137]:
np.argmax(a1)

9

In [138]:
np.argmax(a1, axis = 0)

array([1, 2, 1, 1], dtype=int64)

In [139]:
np.argmax(a1, axis = 1)

array([2, 3, 1], dtype=int64)

In [140]:
np.argmin(a1, axis = 0)

array([0, 0, 2, 2], dtype=int64)

In [141]:
np.argmin(a1, axis = 1)

array([1, 0, 2], dtype=int64)

In [121]:
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [142]:
a1.ravel()         # Converts to single dimension

array([ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3])

In [154]:
a2 = a1.reshape(1,12)
a2

array([[ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3]])

In [155]:
a2.shape

(1, 12)

In [156]:
a2 = a2.squeeze()
a2

array([ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3])

In [157]:
a2.shape

(12,)

In [158]:
a2 = a2.reshape(3,4,1)
a2

array([[[ 2],
        [ 1],
        [ 5],
        [ 4]],

       [[ 3],
        [ 5],
        [ 6],
        [ 7]],

       [[ 3],
        [10],
        [ 2],
        [ 3]]])

In [159]:
a2 = a2.squeeze()
a2

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [160]:
a2.shape

(3, 4)

In [55]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [58]:
a = np.empty((2,3), dtype = int)
a

array([[785177392,       570,         0],
       [        0,    131074,         0]])

### Determinant and Inverse

In [4]:
from numpy.linalg import det, inv, eig
a = np.array([4,3,7,9,2,3,9,6,1,4,7,6,11,4,8,7]).reshape((4,4))
a

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7]])

In [5]:
det(a)

527.0000000000001

In [6]:
inv(a)

array([[-0.0170778 , -0.02087287, -0.07969639,  0.10815939],
       [-0.22580645, -0.38709677,  0.61290323,  0.09677419],
       [-0.10436433,  0.31688805, -0.15370019, -0.0056926 ],
       [ 0.27514231, -0.10815939, -0.04933586, -0.07590133]])

In [7]:
eig(a)

(array([22.97864964,  3.76499269, -4.34011564, -1.40352668]),
 array([[-0.51289911, -0.39468612,  0.5270535 ,  0.05108621],
        [-0.41676444,  0.52758299,  0.07812217, -0.85784205],
        [-0.37954612,  0.5045306 ,  0.33673147,  0.494701  ],
        [-0.64744625, -0.55796767, -0.77635266, -0.12949184]]))

### Concatenation

In [134]:
a1 = np.arange(5)
a2 = np.arange(5,10)

In [135]:
np.concatenate((a1,a2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a1 = np.arange(12).reshape(4,3)
a2 = np.arange(12,24).reshape(4,3)
print(a1)
print(a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [10]:
np.concatenate((a1,a2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [11]:
np.concatenate((a1,a2), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
np.concatenate((a1,a2), axis = 1)

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17],
       [ 6,  7,  8, 18, 19, 20],
       [ 9, 10, 11, 21, 22, 23]])

In [13]:
a1 = a
a2 = a.T
print(a1)
print()
print(a2)

[[ 4  3  7  9]
 [ 2  3  9  6]
 [ 1  4  7  6]
 [11  4  8  7]]

[[ 4  2  1 11]
 [ 3  3  4  4]
 [ 7  9  7  8]
 [ 9  6  6  7]]


In [14]:
np.concatenate((a1,a2), axis = 0)

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7],
       [ 4,  2,  1, 11],
       [ 3,  3,  4,  4],
       [ 7,  9,  7,  8],
       [ 9,  6,  6,  7]])

In [15]:
np.concatenate((a1,a2), axis = 1)

array([[ 4,  3,  7,  9,  4,  2,  1, 11],
       [ 2,  3,  9,  6,  3,  3,  4,  4],
       [ 1,  4,  7,  6,  7,  9,  7,  8],
       [11,  4,  8,  7,  9,  6,  6,  7]])

# Random numbers

In [20]:
np.random.randint(1,10)

1

In [24]:
np.random.randint(50)

5

In [27]:
np.random.randint(1,100,10)

array([49, 29, 90,  9, 53, 62, 61, 72, 70, 71])

In [29]:
np.random.randint(11,100,(10,10))

array([[29, 78, 73, 82, 25, 57, 86, 64, 37, 84],
       [91, 37, 29, 51, 58, 65, 63, 82, 49, 94],
       [99, 80, 15, 80, 60, 33, 43, 37, 75, 55],
       [16, 73, 78, 29, 60, 70, 77, 66, 50, 75],
       [64, 84, 90, 85, 69, 88, 64, 69, 70, 59],
       [99, 82, 98, 94, 58, 88, 27, 77, 78, 68],
       [71, 31, 45, 73, 60, 44, 98, 47, 25, 60],
       [63, 28, 85, 13, 53, 99, 43, 36, 91, 65],
       [94, 64, 61, 80, 76, 76, 66, 20, 52, 40],
       [83, 14, 95, 38, 61, 96, 55, 35, 61, 50]])

In [30]:
np.random.rand(10)

array([0.21799269, 0.38876312, 0.46606122, 0.1258694 , 0.96001441,
       0.65994138, 0.54715397, 0.24126465, 0.51814793, 0.52878755])

In [31]:
np.random.randn(10)

array([-0.71736964, -0.0882393 ,  2.11326286,  0.76335603, -0.50809738,
       -1.56548082,  0.46077007, -0.19166514, -0.5121245 , -1.12468764])

In [32]:
np.random.randn(3,4)

array([[ 0.44366162,  1.24036413,  1.30008374,  0.85710814],
       [-1.93191283, -0.54645057, -0.50337611,  0.70036397],
       [-0.54788566,  0.91285566, -0.6382169 ,  0.87985721]])

# Conditional Indexing

In [33]:
a = np.random.randint(11,100,(8,8))
a

array([[41, 84, 59, 92, 52, 88, 40, 36],
       [12, 55, 48, 62, 41, 86, 86, 48],
       [80, 37, 77, 23, 74, 74, 31, 99],
       [87, 11, 46, 71, 88, 11, 55, 19],
       [39, 59, 54, 22, 90, 21, 18, 38],
       [19, 31, 24, 19, 99, 25, 42, 63],
       [43, 13, 16, 18, 61, 34, 54, 50],
       [24, 20, 76, 80, 54, 29, 81, 85]])

In [34]:
a > 50

array([[False,  True,  True,  True,  True,  True, False, False],
       [False,  True, False,  True, False,  True,  True, False],
       [ True, False,  True, False,  True,  True, False,  True],
       [ True, False, False,  True,  True, False,  True, False],
       [False,  True,  True, False,  True, False, False, False],
       [False, False, False, False,  True, False, False,  True],
       [False, False, False, False,  True, False,  True, False],
       [False, False,  True,  True,  True, False,  True,  True]])

In [37]:
a[a > 50]

array([84, 59, 92, 52, 88, 55, 62, 86, 86, 80, 77, 74, 74, 99, 87, 71, 88,
       55, 59, 54, 90, 99, 63, 61, 54, 76, 80, 54, 81, 85])

In [38]:
a[a < 50]

array([41, 40, 36, 12, 48, 41, 48, 37, 23, 31, 11, 46, 11, 19, 39, 22, 21,
       18, 38, 19, 31, 24, 19, 25, 42, 43, 13, 16, 18, 34, 24, 20, 29])

In [39]:
a[a <= 40]

array([40, 36, 12, 37, 23, 31, 11, 11, 19, 39, 22, 21, 18, 38, 19, 31, 24,
       19, 25, 13, 16, 18, 34, 24, 20, 29])

In [40]:
a[a == 16]

array([16])

# Slicing in Multidimensional Arrays

In [41]:
a = np.random.randint(10,100,(12,12))
a

array([[21, 67, 83, 64, 60, 76, 48, 21, 86, 39, 61, 93],
       [23, 93, 32, 37, 58, 36, 40, 75, 27, 28, 92, 79],
       [20, 20, 44, 45, 59, 12, 39, 48, 33, 25, 17, 71],
       [13, 79, 51, 63, 50, 67, 59, 54, 21, 39, 38, 34],
       [58, 53, 30, 82, 11, 54, 95, 64, 31, 37, 10, 91],
       [23, 36, 62, 36, 14, 71, 73, 46, 75, 83, 19, 53],
       [65, 39, 10, 25, 73, 78, 13, 67, 12, 54, 99, 88],
       [53, 77, 72, 69, 81, 31, 56, 22, 71, 70, 77, 70],
       [59, 80, 42, 94, 59, 24, 49, 53, 85, 68, 78, 38],
       [76, 77, 33, 62, 14, 52, 87, 96, 71, 80, 75, 12],
       [44, 81, 89, 66, 10, 68, 24, 28, 63, 44, 62, 67],
       [79, 29, 46, 85, 55, 59, 61, 94, 56, 51, 44, 73]])

In [42]:
a[0:5]

array([[21, 67, 83, 64, 60, 76, 48, 21, 86, 39, 61, 93],
       [23, 93, 32, 37, 58, 36, 40, 75, 27, 28, 92, 79],
       [20, 20, 44, 45, 59, 12, 39, 48, 33, 25, 17, 71],
       [13, 79, 51, 63, 50, 67, 59, 54, 21, 39, 38, 34],
       [58, 53, 30, 82, 11, 54, 95, 64, 31, 37, 10, 91]])

In [43]:
a[6:11]

array([[65, 39, 10, 25, 73, 78, 13, 67, 12, 54, 99, 88],
       [53, 77, 72, 69, 81, 31, 56, 22, 71, 70, 77, 70],
       [59, 80, 42, 94, 59, 24, 49, 53, 85, 68, 78, 38],
       [76, 77, 33, 62, 14, 52, 87, 96, 71, 80, 75, 12],
       [44, 81, 89, 66, 10, 68, 24, 28, 63, 44, 62, 67]])

In [45]:
a[-6:-1]

array([[65, 39, 10, 25, 73, 78, 13, 67, 12, 54, 99, 88],
       [53, 77, 72, 69, 81, 31, 56, 22, 71, 70, 77, 70],
       [59, 80, 42, 94, 59, 24, 49, 53, 85, 68, 78, 38],
       [76, 77, 33, 62, 14, 52, 87, 96, 71, 80, 75, 12],
       [44, 81, 89, 66, 10, 68, 24, 28, 63, 44, 62, 67]])

In [46]:
a[0:6,0:4]

array([[21, 67, 83, 64],
       [23, 93, 32, 37],
       [20, 20, 44, 45],
       [13, 79, 51, 63],
       [58, 53, 30, 82],
       [23, 36, 62, 36]])

In [47]:
a[2:9:2, 3:8:2]

array([[45, 12, 48],
       [82, 54, 64],
       [25, 78, 67],
       [94, 24, 53]])

In [48]:
a[10:3:-1, 5:10]

array([[68, 24, 28, 63, 44],
       [52, 87, 96, 71, 80],
       [24, 49, 53, 85, 68],
       [31, 56, 22, 71, 70],
       [78, 13, 67, 12, 54],
       [71, 73, 46, 75, 83],
       [54, 95, 64, 31, 37]])

In [61]:
# Take marks of two students in 5 subjects as input and calculate the absolute difference in marks of corresponding subjects
student1 = list(map(int, input('Enter the marks in five subjects for student 1: ').split()))
student2 = list(map(int, input('Enter the marks in five subjects for student 2: ').split()))

student1 = np.array(student1)
student2 = np.array(student2)
diff = np.abs(student1 - student2)
diff

Enter the marks in five subjects for student 1: 80 90 95 90 96
Enter the marks in five subjects for student 2: 90 97 96 72 69


array([10,  7,  1, 18, 27])